language: python
python:
  - 2.7.13  # Debian 9.1
  - 3.5.3   # Debian 9.1
  - 3.6

install:
  - pip install scons
  - scons --version
  - pip install .

script:
  - echo "def foo pass" > foo.py # Test issue #25
  - py.test -v tests
