language: python
python:
  - 3.6
  - 3.7  # Debian Buster
  - nightly

install:
  - pip install scons twine
  - pip install .
  - pip list

script:
  - echo "def foo pass" > foo.py # Test issue #25
  - pytest -v tests
  - python setup.py sdist
  - twine check dist/*
